name: Build-MacOS

on:
  release:
    types:
      - created

jobs:
  build-macos:
    runs-on: macos-latest
    if: |
      startsWith(github.ref, 'refs/tags/zbay')

    steps:
      - uses: actions/checkout@v1.0.0
      - uses: actions/setup-node@master
        with:
          node-version: "12"

      - uses: actions-rs/components-nightly@v1
        with:
          component: clippy

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2020-08-28
          components: clippy
          override: true

      - name: "Set unsafe-perm"
        run: npm set unsafe-perm true

      - name: "Install lerna and electron-builder globally"
        run: npm i -g lerna && npm i -g electron-builder@22.10.5

      - name: "Cache NPM dependencies"
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-

      - name: "Install monorepo dependencies"
        run: npm ci

      - name: "Bootstrap project"
        run: lerna bootstrap

      - name: "Pull tor binary"
        run: export SOURCE_PATH=darwin && lerna run pullBinaries --scope zbay

      - name: "Build on MacOS"
        run: lerna run build:prod --scope zbay

      - name: "Remove crud files"
        run: xattr -cr .

      - name: "Release"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          APPLEID: ${{ secrets.APPLE_ID }}
          APPLEIDPASS: ${{ secrets.APPLE_ID_PASS }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          USE_HARD_LINKS: false
        run: electron-builder -p always --mac -c.publish.path=/sentry-build
