name: Deploy Android to Google Play (internal testing)

on:
  release:
    types: 
      [released]
    paths:
      - packages/mobile/**

jobs:
  build-android:
    timeout-minutes: 25
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - name: "Print OS"
        run: echo ${{ matrix.os }}

      - uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: "Setup environment"
        uses: ./.github/actions/setup-env

      - name: "Install Waggle"
        run: |
          cd ./packages/mobile/nodejs-assets/nodejs-project
          npm ci

      - name: "Remove incompatible dependencies"
        run: |
          cd ./packages/mobile/nodejs-assets/nodejs-project
          rm -rf node_modules/wrtc

      - name: "Apply mobile patch"
        run: |
          cd ./packages/mobile/nodejs-assets/nodejs-project
          patch -f -p0 < modules.patch
          sed -i "s/.*wrtc.*/    \"wrtc\": \"..\/..\/wrtc-mock\"/" node_modules/waggle/package.json
      
      - name: "Prepare signing configuration"
        run: |
          mkdir -p $HOME/.gradle

          printf "\
          ZBAY_UPLOAD_STORE_FILE=zbaymobile.keystore\n\
          ZBAY_UPLOAD_KEY_ALIAS=${{ SECRETS.GOOGLE_KEYSTORE_ALIAS }}
          ZBAY_UPLOAD_STORE_PASSWORD=${{ SECRETS.GOOGLE_KEYSTORE_PASSWORD }}\n\
          ZBAY_UPLOAD_KEY_PASSWORD=${{ SECRETS.GOOGLE_KEYSTORE_PASSWORD }}\
          " > $HOME/.gradle/gradle.properties

          echo ${{ SECRETS.GOOGLE_KEYSTORE }} | base64 --decode > ./packages/mobile/android/app/zbaymobile.keystore

      - name: "Build for Android"
        run: cd ./packages/mobile/android && ./gradlew bundleRelease

      - name: "Upload Artifact"
        uses: actions/upload-artifact@v2
        with:
          name: app-release.aab
          path: ./packages/mobile/android/app/build/outputs/bundle/release/app-release.aab
          retention-days: 5

      - name: "Configure Google Play upload"
        run: |
          mkdir -p distribution/whatsnew
          git log -1 --pretty=format:%s > distribution/whatsnew/whatsnew-pl-PL
          echo ${{ SECRETS.SERVICE_ACCOUNT_JSON }} | base64 --decode > google-play.json
      
      - name: "Upload to Google Play"
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: google-play.json
          packageName: com.zbaymobile
          releaseFiles: ./packages/mobile/android/app/build/outputs/bundle/release/app-release.aab
          track: internal
          whatsNewDirectory: distribution/whatsnew
