name: E2E tests

on: [workflow_call]

# "macos-latest" UnableToAccessScreenRecordingAPIError: The find-window process cannot access the Screen Recording API. https://github.com/DevExpress/testcafe/issues/5352
jobs:
  e2e-linux:
    runs-on: ubuntu-20.04
    timeout-minutes: 20

    env:
      DISPLAY: ":99.0"

    steps:
      - uses: actions/checkout@v2

      - name: Install WM
        run: sudo apt install fluxbox

      - name: Setup environment
        uses: ./.github/actions/setup-env
        with:
          bootstrap-packages: "@quiet/nectar,@quiet/waggle,@quiet/identity,quiet,testcafe-browser-provider-electron,e2e-tests"

      - name: Before build
        uses: ./.github/actions/before-build
        with:
          source-path: linux
      
      - name: Run X11
        run: |
          Xvfb :99 -screen 0 1920x1080x24 &
          sleep 3
          fluxbox &

      - name: Run tests
        run: lerna run test:build --scope e2e-tests --stream
      
      - name: Archive test screenshots
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test-screenshots-linux
          path: packages/e2e-tests/screenshots

  # e2e-windows:
  #   runs-on: windows-2019
  #   timeout-minutes: 20
  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: "Setup environment"
  #       uses: ./.github/actions/setup-env

  #     - name: Build project and run tests
  #       run: lerna run start:e2eWin --scope e2e-tests --stream

  #     - name: Archive test screenshots
  #       uses: actions/upload-artifact@v2
  #       if: always()
  #       with:
  #         name: test-screenshots-windows
  #         path: packages\e2e-tests\screenshots
