name: Deploy iOS to App Center

on:
  release:
    types: 
      [released]
    paths:
      - packages/mobile/**

jobs:
  build-ios:
    timeout-minutes: 25
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - name: "Print OS"
        run: echo ${{ matrix.os }}

      - uses: actions/checkout@v2

      - name: "Install gpg"
        run: brew install gnupg

      - name: "Switch XCode Version"
        run: sudo xcode-select -s /Applications/Xcode_12.4.app

      - name: "Setup environment"
        uses: ./.github/actions/setup-env

      - name: "Install Waggle"
        run: |
          cd ./packages/mobile/nodejs-assets/nodejs-project
          npm ci

      - name: "Remove incompatible dependencies"
        run: |
          cd ./packages/mobile/nodejs-assets/nodejs-project
          rm -rf node_modules/wrtc

      - name: "Apply mobile patch"
        run: |
          cd ./packages/mobile/nodejs-assets/nodejs-project
          patch -f -p0 < modules.patch
          sed -i "s/.*wrtc.*/    \"wrtc\": \"..\/..\/wrtc-mock\"/" node_modules/waggle/package.json
      
      - name: "Cache Pods dependencies"
        uses: actions/cache@v1
        with:
          path: ios/Pods
          key: ${{ runner.OS }}-pods-cache-${{ hashFiles('**/ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.OS }}-pods-cache-

      - name: "Install pod dependencies"
        run: |
          cd ./packages/mobile/ios
          pod install
        shell: bash

      - name: "Setup provisioning profile"
        run: ./.github/secrets/decrypt_secrets.sh
        env:
          IOS_PROFILE_KEY: ${{ secrets.IOS_PROFILE_KEY }}

      - name: "Build for iOS"
        run: |
          cd ./packages/mobile/ios && xcodebuild archive \
            -workspace ZbayMobile.xcworkspace \
            -scheme ZbayMobile \
            -sdk iphoneos14.4 \
            -configuration Release \
            -archivePath $PWD/build/ZbayMobile.xcarchive \
            IPHONEOS_DEPLOYMENT_TARGET=14.1
            PROVISIONING_PROFILE="654a2214-095f-4939-a9e5-09f7a2ccf530" \
            CODE_SIGN_IDENTITY="Apple Distribution: Zbay LLC (CTYKSWN9T4)"
      
      - name: "Export app"
        run: |
          cd ./packages/mobile/ios && xcodebuild \
            -exportArchive \
            -archivePath $PWD/build/ZbayMobile.xcarchive \
            -exportOptionsPlist $PWD/ci.plist \
            -exportPath $PWD/build

      - name: "Upload ipa"
        run: |
          cd ./packages/mobile/ios && xcrun altool --upload-app \
          --type ios \
          --file build/ZbayMobile.ipa \
          -u $APPSTORE_USER -p $APP_PASSWORD \
          --verbose
        env:
          APPSTORE_USER: ${{ secrets.APPSTORE_USER }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
