name: Mobile tests

on:
  pull_request:
    paths:
      - packages/mobile/**

jobs:
  frontend-tests:
    timeout-minutes: 25
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - name: "Print OS"
        run: echo ${{ matrix.os }}

      - uses: actions/checkout@v2

      - name: Setup environment
        uses: ./.github/actions/setup-env
        with:
          bootstrap-packages: "@quiet/logger,@quiet/nectar,@quiet/waggle,@quiet/identity,@quiet/mobile"

      - name: "Unit tests"
        run: lerna run test --scope @quiet/mobile --stream
