name: Scroll regression tests

on:
  pull_request:
    paths:
      - packages/frontend/**

jobs:
  regression-tests:
    timeout-minutes: 25
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - name: "Print OS"
        run: echo ${{ matrix.os }}

      - uses: actions/checkout@v2

      - name: "Setup environment"
        uses: ./.github/actions/setup-env

      - name: "Install libs"
        run: sudo apt-get update && sudo apt-get install -y libgtk2.0-0 libgtk-3-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb

      - name: "Remove test files workaround"
        run: find packages/frontend/src -name '*.test.*' -delete && find packages/waggle/src -name '*.test.*' -delete

      - uses: cypress-io/github-action@v2
        with:
          install: false
          command: npm run regression-test:ci
          working-directory: packages/frontend

      - name: Archive test screenshots
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test-screenshots-linux
          path: packages/frontend/cypress/snapshots